ALTER TABLE "profiles"
ADD COLUMN IF NOT EXISTS "target_weight_kg" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "target_waist_cm" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "target_body_fat_pct" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "target_date" TIMESTAMP(3);
